<a href="https://colab.research.google.com/github/Kaldhendhisrinu/Boosting-/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB
import warnings
warnings.filterwarnings('ignore')

dataset = pd.read_csv('/iris.csv')
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
x=dataset.iloc[:,[0,1,2]]
x

     sepal_length  sepal_width  petal_length
0             5.1          3.5           1.4
1             4.9          3.0           1.4
2             4.7          3.2           1.3
3             4.6          3.1           1.5
4             5.0          3.6           1.4
..            ...          ...           ...
145           6.7          3.0           5.2
146           6.3          2.5           5.0
147           6.5          3.0           5.2
148           6.2          3.4           5.4
149           5.9          3.0           5.1

[150 rows x 3 columns]

In [ ]:
y=dataset.iloc[:,[4]]
y

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

Single = GaussianNB()
Single.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=Single.predict(X_test)
print("predicted values for single Naive Bayes classifier",y_pred)

predicted values for single Naive Bayes classifier ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'virginica' 'virginica' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'setosa'
 'versicolor' 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'setosa' 'virginica' 'virginica' 'versicolor'
 'setosa' 'virginica']

In [ ]:
Acc_single = accuracy_score(y_test,y_pred)*100
print("Accuracy of single Naive Bayes classifier",Acc_single)

Accuracy of single Naive Bayes classifier 86.8421052631579

In [ ]:
cm = confusion_matrix(y_test,y_pred)
print("\n\n Confusion Matrix-using single Naive Bayes Classifier: \n",cm)

 Confusion Matrix-using single Naive Bayes Classifier:
 [[13  0  0]
 [ 0 13  3]
 [ 0  2  7]]

In [ ]:
base_cls = GaussianNB()
num_class = 100

In [ ]:
Bag = BaggingClassifier(estimator=base_cls,n_estimators=num_class,random_state=0)
Bag.fit(X_train,y_train)

BaggingClassifier(estimator=GaussianNB(), n_estimators=100, random_state=0)

In [ ]:
results = model_selection.cross_val_score(Bag,X_test,y_test,cv=10)
print("\n\nAccuracy using Bagged Set of Naive Bayes Classifiers:",results.mean()*100)

Accuracy using Bagged Set of Naive Bayes Classifiers: 86.66666666666666

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier

import warnings
warnings.filterwarnings('ignore')

dataset = pd.read_csv('/iris.csv')
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
x=dataset.iloc[:,[0,1,2]]
x

     sepal_length  sepal_width  petal_length
0             5.1          3.5           1.4
1             4.9          3.0           1.4
2             4.7          3.2           1.3
3             4.6          3.1           1.5
4             5.0          3.6           1.4
..            ...          ...           ...
145           6.7          3.0           5.2
146           6.3          2.5           5.0
147           6.5          3.0           5.2
148           6.2          3.4           5.4
149           5.9          3.0           5.1

[150 rows x 3 columns]

In [ ]:
y=dataset.iloc[:,[4]]
y

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

adaboost = AdaBoostClassifier(n_estimators=100)
adaboost.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
adaboost.score(X_test,y_test)

0.8947368421052632

In [ ]:
y_pred = adaboost.predict(X_test)
print("predicted values for AdaBoostClassifier:")
y_pred

predicted values for AdaBoostClassifier:

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'virginica'], dtype=object)

In [ ]:
Acc_adaboost = accuracy_score(y_test,y_pred)*100
print("\n\n Test Accuracy using AdaBoostClassifier:",Acc_adaboost)

 Test Accuracy using AdaBoostClassifier: 89.47368421052632

In [ ]:
cm = confusion_matrix(y_test,y_pred)
print("\n\n Confusion Matrix-using AdaBoostClassifier: \n",cm)

 Confusion Matrix-using AdaBoostClassifier:
 [[13  0  0]
 [ 0 15  1]
 [ 0  3  6]]

In [1]:
fig, ax = plt.subplots(figsize=(6,6))
ax.imshow(cm)
ax.grid(False)
ax.xaxis.set(ticks=(0,1,2), ticklabels=('Predicted 0', 'Predicted 1', 'Predicted 2'))
ax.yaxis.set(ticks=(0,1,2), ticklabels=('Actual 0', 'Actual 1', 'Actual 2'))
ax.set_ylim(2.5, -0.5)
for i in range(3):
    for j in range(3):
        ax.text(j, i, cm[i, j], ha='center', va='center', color='red')
plt.show()

NameError: name 'plt' is not defined

In [ ]:
import numpy as np
import pand